apiVersion: v1
kind: Pod
metadata: 
 name: pod-test
 namespace: devops
 labels:
  type: test-registry
spec:
 containers:
 - image: localhost:32000/myos:v1
   name: alpine-test
   command: ["sleep"]
   args:
   - "6000"
 imagePullSecrets:
 - name: auth

