apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local
  namespace: devops
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
