apiVersion: v1
kind: PersistentVolume
metadata:
  name: config
spec:
  capacity:
    storage: 20Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: controlplane
    path: /srv/config
    readOnly: no
  claimRef:           
    namespace: default
    name: config
  
