apiVersion: v1
kind: PersistentVolume
metadata:
  name: files
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: controlplane
    path: /srv/files
    readOnly: no
