apiVersion: v1
kind: PersistentVolume
metadata:
  name: marketplace
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: controlplane
    path: /srv/marketplace
    readOnly: no
