apiVersion: v1
kind: PersistentVolume
metadata:
  name: plugin
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: controlplane
    path: /srv/plugin
    readOnly: no
  claimRef:
   namespace: default
   name: plugin 
